### ISSUE TITLE
Multi user support

### ISSUE THREAD

**Issue by goetzk** [voltgrid/django-dnsmanager#4]
Hi,
I'm wondering if dnsmanager supports multiple users managing their own domains or if a separate instance is required per user. I can't see any mention either way in the documentation or a quick skim through the repository.

**Comment by macropin** [comment]
Yes, it does. This can be achieved by the permissions model. Users can be setup to only manage their own zones.

If you need more help implementing this then please reopen. It should probably be documented.

**Comment by goetzk** [comment]
Brilliant, thanks.
